version: "3"
services:
  go:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile_go
    volumes:
      - ../:/go/src/github.com/homma509/9rece/server:cached
    # depends_on:
    #   - dynamodb
    security_opt:
      - seccomp:unconfined
    env_file:
      - ../.env.development
      - ../.env.dynamodb-local
    networks:
      - net
    # tty: true
  sls:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile_sls
    volumes:
      - ../:/opt/app
    env_file:
      - ../.env.aws-config
      - ../.env.aws-credentials
    networks:
      - net
    # tty: true

networks:
  net:
    driver: bridge
