# Application configure

service: nine-rece-frontend

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: nodejs12.x
  region: ${env:REGION_NAME, "ap-northeast-1"}

custom:
  projectName: 9rece-frontend-${self:provider.stage}
  bucketName: ${self:custom.projectName}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: dist/

resources:
  Resources:
    StaticContents:
      Type: AWS::S3::Bucket
      # DeletionPolicy: Retain
      Properties:
        AccessControl: Private
        BucketName: ${self:custom.bucketName}
    StaticContentsS3Policy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticContents
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                    - " "
                    - - "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity"
                      - Ref: StaticCloudFrontOriginAccessIdentity
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - "/"
                  - - { Fn::GetAtt: [StaticContents, Arn] }
                    - "*"
    StaticContentsCloudFront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: "Delivery static contents"
          PriceClass: PriceClass_200
          DefaultRootObject: index.html
          Origins:
            - Id: S3Origin
              DomainName: { Fn::GetAtt: [StaticContents, DomainName] }
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - "/"
                    - - origin-access-identity/cloudfront
                      - Ref: StaticCloudFrontOriginAccessIdentity
          DefaultCacheBehavior:
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            Compress: true
            DefaultTTL: 900
            MaxTTL: 1200
            MinTTL: 600
            ForwardedValues:
              QueryString: true
            SmoothStreaming: false
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: https-only
          CustomErrorResponses:
            - ErrorCachingMinTTL: 300
              ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
    StaticCloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment:
            Ref: AWS::StackName
  Outputs:
    StaticContentsCloudFrontUrl:
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - { Fn::GetAtt: [StaticContentsCloudFront, DomainName] }

plugins:
  - serverless-dotenv-plugin
  - serverless-s3-sync
