version: "3"
services:
  node:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile_node
    ports:
      - "8080:8080"
    volumes:
      - ../:/usr/src
    env_file:
      - ../.env
    networks:
      - net
    # tty: true
  sls:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile_sls
    volumes:
      - ../:/opt/app
    env_file:
      - ../.env.aws-config
      - ../.env.aws-credentials
    networks:
      - net
    # tty: true

networks:
  net:
    driver: bridge
